### ISSUE TITLE
Project roadmap to save the world

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Blockflow#148]
# Project Goal:
Be a visual scripting solution using blocks as their visual representation of functions, using those blocks to determine the application flow.

<details><summary>In case of more context</summary>
I wake up one day and wanted to mix scratch, blockly, gdvelop, construct3 and gamemaker visual scripting in a single tool, to integrate whatever what I wanted without much effort to create a game, and ended doing this.

Somehow is also know as Event Sheet Visual Scripting, so we know now.
</details>

In order to complete these tasks, I try to follow https://github.com/godotengine/godot-visual-script/issues/27 discussion, using it as base to generate solutions to the points mentioned there.

# What's the plan

- [x] **Create a system that defines a function in a visual form.** These are `Commands`, single resources that serves as the representation of a function. Those are our _blocks_.
- [x] **Create a system that tracks the blocks relation.** These are `Collections`, a resource that contains commands, and for specifically tracking the relation between those we have `CommandCollections`.
- [x] **Create a system that uses the block representation to execute their behavior and determines the system flow.** These are our _Processors_, specifically `CommandProcessor`. This node takes a collection of these blocks and executes their functionality, one by one, asking the block itself the next step or determining the next block to use.
- [x] **Define a tool to manipulate the previous created systems.** This is our editor, specifically `BlockflowEditor` (under `editor/`), which is made thinking on editor and runtime scenarios where needed. It works... but just works. Is ugly at my perspective, and some friends have told me that is kinda complex to use, so it is not serving its purpose to be something "easy" to use and understand.
- [ ] **The system that uses the block representation should have a way to determine _when_ it has to execute _something._** For now we handle this manually, requesting the user to do `CommandProcessor.start()`, but the ideal scenario has to remove completely the need to use the script to start the processor. The most simple way would be using signals and boolean values to determine this behavior.
- [ ] **The block definition has to define a way to do something _forward_ and _backwards_.** This can help in scenarios where users, for some reason, want to go back in the visual code, but don't want to _jump_ to that block, but interpolate between all blocks from point A and B. This is currently implemented partially, where _forward_ is just the normal behavior.

## Are we going to generate gdscript?
No, for now _we use GDScript_ to define the functionality, but the flow is determined by the user using the visual tool. In this order, we can't ensure a 1:1 conversion from the visual representation of flow into a single GDScript function. We can try to generate a relative for each command block so is easy to teach the relationship.

<details><summary>Why this issue?</summary>

For some reason I've been busy dealing with human things, so I didn't had the opportunity to work in the project as I wanted to do.

This situation forced me to write somewhere what I wanted this plugin to be, so here we are, reading this paragraph. Thank you, human.
</details>

I'll keep updating this issue to keep track ideas and some stuff that escapes my brain rn.
